
class Info:
    id = 0
    title=  ""
    type = ""
    year = ""
    photo = ""
    description = ""
    # Urls
    amazon_web_link = ""
    amazon_android_link = ""
    amazon_ios_link = ""
    netflix_web_link = ""
    netflix_android_link = ""
    netflix_ios_link = ""
    hotstar_web_link = ""
    hotstar_android_link = ""
    hotstar_ios_link = ""
    hulu_web_link = ""
    hulu_android_link = ""
    hulu_ios_link = ""
    
